apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: argocd
  name: local-pv-3
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: argocd
  name: local-pv-4
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-4
