apiVersion: v1
kind: Service
metadata:
  namespace: argocd
  name: wordpress-intdb
  labels:
    app: wordpress-intdb
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-intdb
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: argocd
  name: wp-pv-claim
  labels:
    app: wordpress-intdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  namespace: argocd
  name: wordpress-intdb
  labels:
    app: wordpress-intdb
spec:
  selector:
    matchLabels:
      app: wordpress-intdb
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-intdb
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wpsecret
              key: password
        ports:
        - containerPort: 80
          name: wordpress-intdb
        volumeMounts:
        - name: wordpress-intdb-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-intdb-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
